### ISSUE TITLE
Move contacts in status-protocol-go

### ISSUE THREAD

**Issue by cammellos** [status-im/status-protocol-go#10]
As a developer
I want to have contacts stored in status-go-protocol
So I don't have to re-implement it myself

### Description
This task involves replacing the persistence layer from status-react to this library.

It needs to fullfil the current API that realm offers https://github.com/status-im/status-react/blob/develop/src/status_im/data_store/contacts.cljs , or equivalent.

It does not involve porting any logic unless necessary, the focus is on making sure an eventual removal of realm will not break data compatibility on future versions.

Depends on #2

### Acceptance criteria
- Contacts (with device info) are stored only in status-protocol-go
- Status-react is integrated

**Comment by StatusWrike** [comment]
➤ Wrike Bot commented:

Adam BabikAndrea Piana All the necessary task dependencies have been completed, so you can start working on it right away.
