### ISSUE TITLE
Add filesystem persistence to MVDS

### ISSUE THREAD

**Issue by cammellos** [status-im/status-protocol-go#15]
As a user
I want to have mvds persistence on the filesystem
so that I can improve the reliability of sending messaging even across restarts

### Description

Currently MVDS is using an in-memory storage, which gets erased across restarts.
We should be storing this information in the database.
Messages should be encrypted with the user password, similarly to the rest of the data persisted (sqlcipher + sqlite).

Sync state and epoch is the data to be persisted.

See: https://github.com/status-im/status-console-client/issues/120 and https://github.com/status-im/status-console-client/issues/119
### Acceptance criteria

- MVDS use filesystem persistence and information is kept across restarts

**Comment by rachelhamlin** [comment]
@adambabik @cammellos this is currently scoped under the code freeze milestone—does it still need to be completed by the 30th? Is it actually finished?

**Comment by cammellos** [comment]
this has now been merged in status-react and it can be closed
