### ISSUE TITLE
Integrate status-protocol-go with status-react

### ISSUE THREAD

**Issue by cammellos** [status-im/status-protocol-go#2]
As a developer
I would like to have `status-protocol-go` to be integrated with `status-react`
So that any change to the `StatusProtocol` is isolated and other clients can re-use this library

### Description

This library should be integrated with status-react via status-go.

For it to be working without any change in status-react:

- Disabling storing of messages (optional, we don't want to duplicate messages for now, although not a problem)
- Disable fetching of messages from mailserver in this layer (probably best, might be already disabled/removed)
- Disable storing of chats (optional as part of this task, #3)
- Disable parsing of transit (optional, but we need to surface the payload encoded payload to status-react, as that's what it expects + not all messages have been ported)

Changes in API in status-react/status-go can be made to accommodate the integration, as long as functionalities are maintained. 

Backward compatibility between the resulting status-go version and status-react is not needed (i.e is fine if the version of status-go that includes this library is not compatible with current status-react, if that's the case care must be taken not to merge too early and have `develop` of status-go not compatible with `develop` of status-react, in order to avoid potentially blocking other developers, if incompatible I would delay merging until successfully QAed).

### Acceptance criteria

- Status react is using `status-protocol-go` for sending/encryption

**Comment by oskarth** [comment]
@adambabik is there a corresponding issue on status-react for this? What's the rough ETA/effort on this one?

**Comment by adambabik** [comment]
@oskarth it is now as I finished work in status-go and status-protocol-go repos. Please check out https://github.com/status-im/status-react/issues/8604.
