### ISSUE TITLE
Move chats  in status-protocol-go

### ISSUE THREAD

**Issue by cammellos** [status-im/status-protocol-go#3]
As a developer
I would like to have chats stored in status-protocol-go
So that clients don't have to implement their own persistence of chats

### Description

Public/one-to-one/group chats should be stored in status-go.

The minimum outcome is that simply the data layer is replaced with the one provided in this task.
That includes migrating group chats data such as `membership-updates`.

Any field that is currently not used by status-react can be removed (`tags`).

Ideally status-react is provided with exactly the same structure as it is now, to minimize changes.
A migration for existing clients is advised but not necessary. Care must be taken if data compatibility is broken to ensure it will not be merged before the release.

Depends on #2

### Acceptance criteria

- Chats are stored in status-protocol-go
- Integrated with status-react

**Comment by StatusWrike** [comment]
➤ Wrike Bot commented:

Andrea Piana All the necessary task dependencies have been completed, so you can start working on it right away.

**Comment by StatusWrike** [comment]
➤ Nabil Naghdy commented:

Is this still launch blocking?

**Comment by cammellos** [comment]
It's still in V1 scope, but it's not blocked anymore, it's ready to pick up, currently devs are on other v1 tasks though, but likely to be picked up next.

**Comment by cammellos** [comment]
merged in status-react
