### ISSUE TITLE
Prepare API for alternative ETH node implementations

### ISSUE THREAD

**Issue by PombeirP** [status-im/status-protocol-go#84]
Currently, there are areas in the code that leak Geth types, making it impossible to have status-protocol-go work with e.g. Nimbus.

### Issues

- [x] `NewMessenger` is receiving a Geth type `*whisper.Whisper`;
- [x] `whisper.BytesToTopic` needs to be encapsulated;
- [x] `WhisperServiceTransport.RetrieveAllMessages` is returning a Geth type (`*whisper.ReceivedMessage`), tying the consuming class `Messenger` to Geth;
- [x] `messageProcessor.Process` receives `*whisper.ReceivedMessage`.

### Implementation

To fix that we need to create interfaces/wrappers for:
  - [x] `whisper.Whisper`
  - [x] `whisper.PublicWhisperAPI`
  - [x] `whisper.Filter`
    - [x] Factory method on Whisper interface that creates appropriate `Filter` wrapper object instances
  - [x] `whisper.NewMessage`
  - [x] `whisper.ReceivedMessage`
  - [x] `whisper.MessageStore`
  - [x] `whisper.BytesToTopic`
  - [x] Fix tests
  - Optional:
    - [x] `envelopesMonitorConfig`

### Next steps

- Implement Nimbus support
- Have status-console-client work on top of Nimbus

cc @adambabik @cammellos

**Comment by PombeirP** [comment]
@cammellos/@adambabik status-console-client seems quite out of date (`master` is 2 months old). There is an `upgrade-status-protocol-go` but that one also points to a non-existing status-protocol-go commit.

**Comment by PombeirP** [comment]
Oh, I thought NewMessenger was called from status-console-client, but it's actually being done from status-go :-/

```
# github.com/status-im/status-go/services/shhext
vendor/github.com/status-im/status-go/services/shhext/service.go:138:4: cannot use s.w (type *whisperv6.Whisper) as type statusprototypes.WhisperInterface in argument to "github.com/status-im/status-protocol-go".NewMessenger:
        *whisperv6.Whisper does not implement statusprototypes.WhisperInterface (wrong type for GetFilter method)
                have GetFilter(string) *whisperv6.Filter
                want GetFilter(string) statusprototypes.Filter
```

**Comment by adambabik** [comment]
Yeah, `NewMessenger` is called from anything that wants to use status-protocol-go. Generally, any public interface changes in the main package of status-protocol-go can potentially break something at this point.
